language: ruby
sudo: false

rvm:
  - 2.2.7
  - 2.3.3
  - 2.4.1
  - ruby-head

gemfile:
  - gemfiles/Gemfile-rails4.1.x
  - gemfiles/Gemfile-rails4.2.x
  - gemfiles/Gemfile-rails5.0.x
  - gemfiles/Gemfile-rails5.1.x
  - gemfiles/Gemfile-rails_edge

matrix:
  allow_failures:
    - rvm: 2.2.7
      gemfile: gemfiles/Gemfile-rails_edge
    - rvm: 2.3.3
      gemfile: gemfiles/Gemfile-rails_edge
    - rvm: 2.4.1
      gemfile: gemfiles/Gemfile-rails_edge
    - rvm: ruby-head
      gemfile: gemfiles/Gemfile-rails4.1.x
    - rvm: ruby-head
      gemfile: gemfiles/Gemfile-rails4.2.x
    - rvm: ruby-head
      gemfile: gemfiles/Gemfile-rails5.0.x
    - rvm: ruby-head
      gemfile: gemfiles/Gemfile-rails5.1.x
    - rvm: ruby-head
      gemfile: gemfiles/Gemfile-rails_edge
